	.TIME

	.INSERT "M3FREQ"
	.INSERT "M3DAT"			; DATA IS IN THIS FILE
	.INSERT "MACROS"
	.INSERT "SYNTAX"
	.INSERT "DEBUG"
	.INSERT "GOAL"
	.INSERT "CLOCK"
	.INSERT "MAIN"
	.INSERT "PARSER"
	.INSERT "VERBS"
	.INSERT "PLACES"
	.INSERT "PEOPLE"
	.INSERT "THINGS"
	.INSERT "EVENTS"
	.INSERT "M3STR"
	.END
